apiVersion: v1
kind: Service
metadata:
  name: hostnamedemo-service
spec:
  selector:
    app: hostnamedemo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  externalIPs:
    - 40.81.225.172
