name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Docker build of hostname
        run: docker build -t hostname:v1.0 .
      - uses: Azure/docker-login@v1
        with:
         login-server: hostname.azurecr.io
         username: ${{ secrets.ACR_USERNAME }}
         password: ${{ secrets.ACR_PASSWORD }}
    
      - run: |
         docker build . -t hostname.azurecr.io/hostname:${{ github.sha }}
         docker push hostname.azurecr.io/hostname:${{ github.sha }}
      - uses: Azure/aks-set-context@v1
        with:
         creds: '${{ secrets.AZURE_CREDENTIALS }}'
         cluster-name: hostname
         resource-group: Demo-HostName
      - uses: azure/k8s-actions/setup-kubectl@master
        with:
         version: '<version>' # default is latest stable
         id: install
      - uses: Azure/k8s-create-secret@v1
        with:
         container-registry-url: hostname.azurecr.io
         container-registry-username: ${{ secrets.ACR_USERNAME }}
         container-registry-password: ${{ secrets.ACR_PASSWORD }}
         secret-name: k8s-secret
      - uses: Azure/k8s-deploy@v1
        with:
         manifests: |
          manifests/hostname-deployment.yml
          manifests/hostname-service.yml
         images: |
          hostname.azurecr.io/hostname:${{ github.sha }}
         imagepullsecrets: |
          k8s-secret
        
